### ISSUE TITLE
Possible bug with file upload inside edit page

### ISSUE THREAD

**Issue by Dmitrev** [pyrocms/pyrocms#3647]
I have a fresh install of Pyrocms 3, with code: 
```composer create-project pyrocms/pyrocms=3.0-beta3 --prefer-dist```

Screenshot, when i try to upload a file in the "edit page"-page
![screenshot](http://i.imgur.com/Ez4uG3y.png)

I can however upload an image just by going to the "Files" page. So it's not a permissions issue i assume.

**Comment by RyanThompson** [comment]
What's your environment look like? Domain / dev path / dev domain and what URL is it trying to call (look at your debugger's network activity).

Little more information and we can get to the bottom of this!

**Comment by Dmitrev** [comment]
I've looked into the network activity and the request is made via AJAX when you are in the "Edit page". 

My base url is:
```http://localhost/pyrocms/public```

And the request points to:
```http://localhost/streams/wysiwyg-field_type/handle```
Which obviously does not exist

If you go to `/admin/files` the request is not made with AJAX, that's why it works.


To fix this we need to give the ajax request the base url of the application, i need to dig into the code to find the exact spot.

**Comment by RyanThompson** [comment]
What is your app domain you’re running on?

**Comment by Dmitrev** [comment]
I'm running it on`http://localhost/pyrocms/public` it's not running of a domain.

**Comment by RyanThompson** [comment]
What is the JS value of APPLICATION_URL in your <head> when editing a page?

**Comment by RyanThompson** [comment]
You might have to make a virtual domain though.

**Comment by Dmitrev** [comment]
I'll try a V-host setup, it should bypass this issue.

Here is the output from the console, notice that it also tries to pull assets via the wrong URL:
![image](https://cloud.githubusercontent.com/assets/1260209/13738056/59c1498a-e9c2-11e5-9de8-071775a470e6.png)

**Comment by RyanThompson** [comment]
Can you composer update, run php artisan asset:clear and php artisan twig:clean and try again with your current configuration. I believe I fixed it.

**Comment by Dmitrev** [comment]
Doesn't seem to be fixed for me.

![image](https://cloud.githubusercontent.com/assets/1260209/13751364/23862e24-ea0a-11e5-9323-2025f99b9f08.png)

A temporary fix would be a v-host setup. I'll will try to help you resolve this, i'm kinda new to the core code.

**Comment by RyanThompson** [comment]
In your .env file can you change the APPLICATION_DOMAIN to localhost/pyrocms/public and see if that helps.

**Comment by nickstanko** [comment]
![imageupload](https://cloud.githubusercontent.com/assets/989922/21015339/95942180-bd2f-11e6-9c54-aba3873d1127.png)

We are setup with a v-host and still having issues with this bug. Please advise what we could try. We ran composer update and cleared cache.

**Comment by RyanThompson** [comment]
What do your laravel error logs say? That 500 error will be logged.

**Comment by RyanThompson** [comment]
This should be remedied with the addition of `REQUEST_ROOT_PATH + ` to the AJAX calls. Can you update and clear assets and try again?
